language: java

jdk:
  - openjdk14

sudo: false

before_install:
  - chmod +x mvnw

env:
  global:
    - CODECOV_TOKEN="fd83ef1a-bfc7-487b-8efc-ad4969717651"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -emelyanov.am@gmail.com
    on_success: never # default: change
    on_failure: always # default: always